/*
 * generated by Xtext
 */
package org.eclipse.papyrusrt.xtumlrt.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class UmlrtStandaloneSetup extends UmlrtStandaloneSetupGenerated{

	public static void doSetup() {
		new UmlrtStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

