/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.hclscope.ide;


/**
 * Use this class to register ide components.
 */
public class HclScopeIdeModule extends AbstractHclScopeIdeModule {
}
