/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.hclscope.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.hclscope.HclScopeRuntimeModule;
import org.xtext.example.hclscope.HclScopeStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class HclScopeIdeSetup extends HclScopeStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new HclScopeRuntimeModule(), new HclScopeIdeModule()));
	}
	
}
