/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.hclscope.hclScope;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Choice</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getChoice()
 * @model
 * @generated
 */
public interface Choice extends Vertex
{
} // Choice
