/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.hclscope.hclScope;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entry Point</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getEntryPoint()
 * @model
 * @generated
 */
public interface EntryPoint extends Vertex
{
} // EntryPoint
