/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.hclscope.hclScope;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.hclscope.hclScope.HclScopeFactory
 * @model kind="package"
 * @generated
 */
public interface HclScopePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "hclScope";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/hclscope/HclScope";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "hclScope";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  HclScopePackage eINSTANCE = org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.StateMachineImpl <em>State Machine</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.StateMachineImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getStateMachine()
   * @generated
   */
  int STATE_MACHINE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE__NAME = 0;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE__STATES = 1;

  /**
   * The feature id for the '<em><b>Initialtransition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE__INITIALTRANSITION = 2;

  /**
   * The feature id for the '<em><b>Junction</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE__JUNCTION = 3;

  /**
   * The feature id for the '<em><b>Choice</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE__CHOICE = 4;

  /**
   * The feature id for the '<em><b>Transition</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE__TRANSITION = 5;

  /**
   * The number of structural features of the '<em>State Machine</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_MACHINE_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.VertexImpl <em>Vertex</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.VertexImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getVertex()
   * @generated
   */
  int VERTEX = 24;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX__NAME = 0;

  /**
   * The number of structural features of the '<em>Vertex</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.StateImpl <em>State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.StateImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getState()
   * @generated
   */
  int STATE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__NAME = VERTEX__NAME;

  /**
   * The feature id for the '<em><b>Internaltransition</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__INTERNALTRANSITION = VERTEX_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Entryaction</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__ENTRYACTION = VERTEX_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Exitaction</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__EXITACTION = VERTEX_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Entrypoint</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__ENTRYPOINT = VERTEX_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Exitpoint</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__EXITPOINT = VERTEX_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__STATES = VERTEX_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Initialtransition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__INITIALTRANSITION = VERTEX_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Junction</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__JUNCTION = VERTEX_FEATURE_COUNT + 7;

  /**
   * The feature id for the '<em><b>Choice</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__CHOICE = VERTEX_FEATURE_COUNT + 8;

  /**
   * The feature id for the '<em><b>Transition</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__TRANSITION = VERTEX_FEATURE_COUNT + 9;

  /**
   * The feature id for the '<em><b>Historytransition</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__HISTORYTRANSITION = VERTEX_FEATURE_COUNT + 10;

  /**
   * The number of structural features of the '<em>State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_FEATURE_COUNT = VERTEX_FEATURE_COUNT + 11;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.EntryActionImpl <em>Entry Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.EntryActionImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getEntryAction()
   * @generated
   */
  int ENTRY_ACTION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRY_ACTION__NAME = 0;

  /**
   * The number of structural features of the '<em>Entry Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRY_ACTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.ExitActionImpl <em>Exit Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.ExitActionImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getExitAction()
   * @generated
   */
  int EXIT_ACTION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXIT_ACTION__NAME = 0;

  /**
   * The number of structural features of the '<em>Exit Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXIT_ACTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.InitialStateImpl <em>Initial State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.InitialStateImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getInitialState()
   * @generated
   */
  int INITIAL_STATE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_STATE__NAME = 0;

  /**
   * The number of structural features of the '<em>Initial State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_STATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.JunctionImpl <em>Junction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.JunctionImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getJunction()
   * @generated
   */
  int JUNCTION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JUNCTION__NAME = VERTEX__NAME;

  /**
   * The number of structural features of the '<em>Junction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JUNCTION_FEATURE_COUNT = VERTEX_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.ChoiceImpl <em>Choice</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.ChoiceImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getChoice()
   * @generated
   */
  int CHOICE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE__NAME = VERTEX__NAME;

  /**
   * The number of structural features of the '<em>Choice</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_FEATURE_COUNT = VERTEX_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.EntryPointImpl <em>Entry Point</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.EntryPointImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getEntryPoint()
   * @generated
   */
  int ENTRY_POINT = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRY_POINT__NAME = VERTEX__NAME;

  /**
   * The number of structural features of the '<em>Entry Point</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRY_POINT_FEATURE_COUNT = VERTEX_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.ExitPointImpl <em>Exit Point</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.ExitPointImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getExitPoint()
   * @generated
   */
  int EXIT_POINT = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXIT_POINT__NAME = VERTEX__NAME;

  /**
   * The number of structural features of the '<em>Exit Point</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXIT_POINT_FEATURE_COUNT = VERTEX_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.DeepHistoryImpl <em>Deep History</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.DeepHistoryImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getDeepHistory()
   * @generated
   */
  int DEEP_HISTORY = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEEP_HISTORY__NAME = 0;

  /**
   * The number of structural features of the '<em>Deep History</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEEP_HISTORY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.TransitionsImpl <em>Transitions</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.TransitionsImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getTransitions()
   * @generated
   */
  int TRANSITIONS = 25;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITIONS__NAME = 0;

  /**
   * The feature id for the '<em><b>Transitionbody</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITIONS__TRANSITIONBODY = 1;

  /**
   * The number of structural features of the '<em>Transitions</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITIONS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.InitialTransitionImpl <em>Initial Transition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.InitialTransitionImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getInitialTransition()
   * @generated
   */
  int INITIAL_TRANSITION = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_TRANSITION__NAME = TRANSITIONS__NAME;

  /**
   * The feature id for the '<em><b>Transitionbody</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_TRANSITION__TRANSITIONBODY = TRANSITIONS__TRANSITIONBODY;

  /**
   * The feature id for the '<em><b>Initialstate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_TRANSITION__INITIALSTATE = TRANSITIONS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Initialto</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_TRANSITION__INITIALTO = TRANSITIONS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Initial Transition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_TRANSITION_FEATURE_COUNT = TRANSITIONS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.TransitionImpl <em>Transition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.TransitionImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getTransition()
   * @generated
   */
  int TRANSITION = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__NAME = TRANSITIONS__NAME;

  /**
   * The feature id for the '<em><b>Transitionbody</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__TRANSITIONBODY = TRANSITIONS__TRANSITIONBODY;

  /**
   * The feature id for the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__FROM = TRANSITIONS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__TO = TRANSITIONS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Transition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_FEATURE_COUNT = TRANSITIONS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.InternalTransitionImpl <em>Internal Transition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.InternalTransitionImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getInternalTransition()
   * @generated
   */
  int INTERNAL_TRANSITION = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERNAL_TRANSITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Transitionbody</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERNAL_TRANSITION__TRANSITIONBODY = 1;

  /**
   * The number of structural features of the '<em>Internal Transition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERNAL_TRANSITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.HistoryTransitionImpl <em>History Transition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.HistoryTransitionImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getHistoryTransition()
   * @generated
   */
  int HISTORY_TRANSITION = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HISTORY_TRANSITION__NAME = TRANSITIONS__NAME;

  /**
   * The feature id for the '<em><b>Transitionbody</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HISTORY_TRANSITION__TRANSITIONBODY = TRANSITIONS__TRANSITIONBODY;

  /**
   * The feature id for the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HISTORY_TRANSITION__FROM = TRANSITIONS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>To</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HISTORY_TRANSITION__TO = TRANSITIONS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>History Transition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HISTORY_TRANSITION_FEATURE_COUNT = TRANSITIONS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.TransitionBodyImpl <em>Transition Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.TransitionBodyImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getTransitionBody()
   * @generated
   */
  int TRANSITION_BODY = 14;

  /**
   * The feature id for the '<em><b>Methodparameter</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_BODY__METHODPARAMETER = 0;

  /**
   * The feature id for the '<em><b>Portevent</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_BODY__PORTEVENT = 1;

  /**
   * The feature id for the '<em><b>Trigger</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_BODY__TRIGGER = 2;

  /**
   * The feature id for the '<em><b>Transitionguard</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_BODY__TRANSITIONGUARD = 3;

  /**
   * The feature id for the '<em><b>Transitionoperation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_BODY__TRANSITIONOPERATION = 4;

  /**
   * The number of structural features of the '<em>Transition Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_BODY_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.TransitionGuardImpl <em>Transition Guard</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.TransitionGuardImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getTransitionGuard()
   * @generated
   */
  int TRANSITION_GUARD = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_GUARD__NAME = 0;

  /**
   * The number of structural features of the '<em>Transition Guard</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_GUARD_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.TransitionOperationImpl <em>Transition Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.TransitionOperationImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getTransitionOperation()
   * @generated
   */
  int TRANSITION_OPERATION = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_OPERATION__NAME = 0;

  /**
   * The number of structural features of the '<em>Transition Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_OPERATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.TriggerImpl <em>Trigger</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.TriggerImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getTrigger()
   * @generated
   */
  int TRIGGER = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__NAME = 0;

  /**
   * The number of structural features of the '<em>Trigger</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.MethodImpl <em>Method</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.MethodImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getMethod()
   * @generated
   */
  int METHOD = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__NAME = 0;

  /**
   * The number of structural features of the '<em>Method</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.ParameterImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NAME = 0;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.MethodParameterTriggerImpl <em>Method Parameter Trigger</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.MethodParameterTriggerImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getMethodParameterTrigger()
   * @generated
   */
  int METHOD_PARAMETER_TRIGGER = 20;

  /**
   * The feature id for the '<em><b>Method</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_PARAMETER_TRIGGER__METHOD = 0;

  /**
   * The feature id for the '<em><b>Parameter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_PARAMETER_TRIGGER__PARAMETER = 1;

  /**
   * The number of structural features of the '<em>Method Parameter Trigger</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_PARAMETER_TRIGGER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.PortImpl <em>Port</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.PortImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getPort()
   * @generated
   */
  int PORT = 21;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT__NAME = 0;

  /**
   * The number of structural features of the '<em>Port</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.EventImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getEvent()
   * @generated
   */
  int EVENT = 22;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.hclscope.hclScope.impl.PortEventTriggerImpl <em>Port Event Trigger</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.hclscope.hclScope.impl.PortEventTriggerImpl
   * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getPortEventTrigger()
   * @generated
   */
  int PORT_EVENT_TRIGGER = 23;

  /**
   * The feature id for the '<em><b>Port</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_EVENT_TRIGGER__PORT = 0;

  /**
   * The feature id for the '<em><b>Event</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_EVENT_TRIGGER__EVENT = 1;

  /**
   * The number of structural features of the '<em>Port Event Trigger</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_EVENT_TRIGGER_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.StateMachine <em>State Machine</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State Machine</em>'.
   * @see org.xtext.example.hclscope.hclScope.StateMachine
   * @generated
   */
  EClass getStateMachine();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hclscope.hclScope.StateMachine#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hclscope.hclScope.StateMachine#getName()
   * @see #getStateMachine()
   * @generated
   */
  EAttribute getStateMachine_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hclscope.hclScope.StateMachine#getStates <em>States</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>States</em>'.
   * @see org.xtext.example.hclscope.hclScope.StateMachine#getStates()
   * @see #getStateMachine()
   * @generated
   */
  EReference getStateMachine_States();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.hclscope.hclScope.StateMachine#getInitialtransition <em>Initialtransition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Initialtransition</em>'.
   * @see org.xtext.example.hclscope.hclScope.StateMachine#getInitialtransition()
   * @see #getStateMachine()
   * @generated
   */
  EReference getStateMachine_Initialtransition();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hclscope.hclScope.StateMachine#getJunction <em>Junction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Junction</em>'.
   * @see org.xtext.example.hclscope.hclScope.StateMachine#getJunction()
   * @see #getStateMachine()
   * @generated
   */
  EReference getStateMachine_Junction();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hclscope.hclScope.StateMachine#getChoice <em>Choice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Choice</em>'.
   * @see org.xtext.example.hclscope.hclScope.StateMachine#getChoice()
   * @see #getStateMachine()
   * @generated
   */
  EReference getStateMachine_Choice();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hclscope.hclScope.StateMachine#getTransition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Transition</em>'.
   * @see org.xtext.example.hclscope.hclScope.StateMachine#getTransition()
   * @see #getStateMachine()
   * @generated
   */
  EReference getStateMachine_Transition();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State</em>'.
   * @see org.xtext.example.hclscope.hclScope.State
   * @generated
   */
  EClass getState();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hclscope.hclScope.State#getInternaltransition <em>Internaltransition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Internaltransition</em>'.
   * @see org.xtext.example.hclscope.hclScope.State#getInternaltransition()
   * @see #getState()
   * @generated
   */
  EReference getState_Internaltransition();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hclscope.hclScope.State#getEntryaction <em>Entryaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entryaction</em>'.
   * @see org.xtext.example.hclscope.hclScope.State#getEntryaction()
   * @see #getState()
   * @generated
   */
  EReference getState_Entryaction();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hclscope.hclScope.State#getExitaction <em>Exitaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exitaction</em>'.
   * @see org.xtext.example.hclscope.hclScope.State#getExitaction()
   * @see #getState()
   * @generated
   */
  EReference getState_Exitaction();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hclscope.hclScope.State#getEntrypoint <em>Entrypoint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entrypoint</em>'.
   * @see org.xtext.example.hclscope.hclScope.State#getEntrypoint()
   * @see #getState()
   * @generated
   */
  EReference getState_Entrypoint();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hclscope.hclScope.State#getExitpoint <em>Exitpoint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exitpoint</em>'.
   * @see org.xtext.example.hclscope.hclScope.State#getExitpoint()
   * @see #getState()
   * @generated
   */
  EReference getState_Exitpoint();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hclscope.hclScope.State#getStates <em>States</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>States</em>'.
   * @see org.xtext.example.hclscope.hclScope.State#getStates()
   * @see #getState()
   * @generated
   */
  EReference getState_States();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.hclscope.hclScope.State#getInitialtransition <em>Initialtransition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Initialtransition</em>'.
   * @see org.xtext.example.hclscope.hclScope.State#getInitialtransition()
   * @see #getState()
   * @generated
   */
  EReference getState_Initialtransition();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hclscope.hclScope.State#getJunction <em>Junction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Junction</em>'.
   * @see org.xtext.example.hclscope.hclScope.State#getJunction()
   * @see #getState()
   * @generated
   */
  EReference getState_Junction();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hclscope.hclScope.State#getChoice <em>Choice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Choice</em>'.
   * @see org.xtext.example.hclscope.hclScope.State#getChoice()
   * @see #getState()
   * @generated
   */
  EReference getState_Choice();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hclscope.hclScope.State#getTransition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Transition</em>'.
   * @see org.xtext.example.hclscope.hclScope.State#getTransition()
   * @see #getState()
   * @generated
   */
  EReference getState_Transition();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hclscope.hclScope.State#getHistorytransition <em>Historytransition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Historytransition</em>'.
   * @see org.xtext.example.hclscope.hclScope.State#getHistorytransition()
   * @see #getState()
   * @generated
   */
  EReference getState_Historytransition();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.EntryAction <em>Entry Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entry Action</em>'.
   * @see org.xtext.example.hclscope.hclScope.EntryAction
   * @generated
   */
  EClass getEntryAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hclscope.hclScope.EntryAction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hclscope.hclScope.EntryAction#getName()
   * @see #getEntryAction()
   * @generated
   */
  EAttribute getEntryAction_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.ExitAction <em>Exit Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exit Action</em>'.
   * @see org.xtext.example.hclscope.hclScope.ExitAction
   * @generated
   */
  EClass getExitAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hclscope.hclScope.ExitAction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hclscope.hclScope.ExitAction#getName()
   * @see #getExitAction()
   * @generated
   */
  EAttribute getExitAction_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.InitialState <em>Initial State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Initial State</em>'.
   * @see org.xtext.example.hclscope.hclScope.InitialState
   * @generated
   */
  EClass getInitialState();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hclscope.hclScope.InitialState#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hclscope.hclScope.InitialState#getName()
   * @see #getInitialState()
   * @generated
   */
  EAttribute getInitialState_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.Junction <em>Junction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Junction</em>'.
   * @see org.xtext.example.hclscope.hclScope.Junction
   * @generated
   */
  EClass getJunction();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.Choice <em>Choice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Choice</em>'.
   * @see org.xtext.example.hclscope.hclScope.Choice
   * @generated
   */
  EClass getChoice();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.EntryPoint <em>Entry Point</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entry Point</em>'.
   * @see org.xtext.example.hclscope.hclScope.EntryPoint
   * @generated
   */
  EClass getEntryPoint();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.ExitPoint <em>Exit Point</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exit Point</em>'.
   * @see org.xtext.example.hclscope.hclScope.ExitPoint
   * @generated
   */
  EClass getExitPoint();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.DeepHistory <em>Deep History</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Deep History</em>'.
   * @see org.xtext.example.hclscope.hclScope.DeepHistory
   * @generated
   */
  EClass getDeepHistory();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hclscope.hclScope.DeepHistory#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hclscope.hclScope.DeepHistory#getName()
   * @see #getDeepHistory()
   * @generated
   */
  EAttribute getDeepHistory_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.InitialTransition <em>Initial Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Initial Transition</em>'.
   * @see org.xtext.example.hclscope.hclScope.InitialTransition
   * @generated
   */
  EClass getInitialTransition();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.hclscope.hclScope.InitialTransition#getInitialstate <em>Initialstate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Initialstate</em>'.
   * @see org.xtext.example.hclscope.hclScope.InitialTransition#getInitialstate()
   * @see #getInitialTransition()
   * @generated
   */
  EReference getInitialTransition_Initialstate();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.hclscope.hclScope.InitialTransition#getInitialto <em>Initialto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Initialto</em>'.
   * @see org.xtext.example.hclscope.hclScope.InitialTransition#getInitialto()
   * @see #getInitialTransition()
   * @generated
   */
  EReference getInitialTransition_Initialto();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.Transition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition</em>'.
   * @see org.xtext.example.hclscope.hclScope.Transition
   * @generated
   */
  EClass getTransition();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.hclscope.hclScope.Transition#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>From</em>'.
   * @see org.xtext.example.hclscope.hclScope.Transition#getFrom()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_From();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.hclscope.hclScope.Transition#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>To</em>'.
   * @see org.xtext.example.hclscope.hclScope.Transition#getTo()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_To();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.InternalTransition <em>Internal Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Internal Transition</em>'.
   * @see org.xtext.example.hclscope.hclScope.InternalTransition
   * @generated
   */
  EClass getInternalTransition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hclscope.hclScope.InternalTransition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hclscope.hclScope.InternalTransition#getName()
   * @see #getInternalTransition()
   * @generated
   */
  EAttribute getInternalTransition_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.hclscope.hclScope.InternalTransition#getTransitionbody <em>Transitionbody</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Transitionbody</em>'.
   * @see org.xtext.example.hclscope.hclScope.InternalTransition#getTransitionbody()
   * @see #getInternalTransition()
   * @generated
   */
  EReference getInternalTransition_Transitionbody();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.HistoryTransition <em>History Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>History Transition</em>'.
   * @see org.xtext.example.hclscope.hclScope.HistoryTransition
   * @generated
   */
  EClass getHistoryTransition();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.hclscope.hclScope.HistoryTransition#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>From</em>'.
   * @see org.xtext.example.hclscope.hclScope.HistoryTransition#getFrom()
   * @see #getHistoryTransition()
   * @generated
   */
  EReference getHistoryTransition_From();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.hclscope.hclScope.HistoryTransition#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>To</em>'.
   * @see org.xtext.example.hclscope.hclScope.HistoryTransition#getTo()
   * @see #getHistoryTransition()
   * @generated
   */
  EReference getHistoryTransition_To();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.TransitionBody <em>Transition Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition Body</em>'.
   * @see org.xtext.example.hclscope.hclScope.TransitionBody
   * @generated
   */
  EClass getTransitionBody();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hclscope.hclScope.TransitionBody#getMethodparameter <em>Methodparameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Methodparameter</em>'.
   * @see org.xtext.example.hclscope.hclScope.TransitionBody#getMethodparameter()
   * @see #getTransitionBody()
   * @generated
   */
  EReference getTransitionBody_Methodparameter();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hclscope.hclScope.TransitionBody#getPortevent <em>Portevent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Portevent</em>'.
   * @see org.xtext.example.hclscope.hclScope.TransitionBody#getPortevent()
   * @see #getTransitionBody()
   * @generated
   */
  EReference getTransitionBody_Portevent();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.hclscope.hclScope.TransitionBody#getTrigger <em>Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Trigger</em>'.
   * @see org.xtext.example.hclscope.hclScope.TransitionBody#getTrigger()
   * @see #getTransitionBody()
   * @generated
   */
  EReference getTransitionBody_Trigger();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.hclscope.hclScope.TransitionBody#getTransitionguard <em>Transitionguard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Transitionguard</em>'.
   * @see org.xtext.example.hclscope.hclScope.TransitionBody#getTransitionguard()
   * @see #getTransitionBody()
   * @generated
   */
  EReference getTransitionBody_Transitionguard();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.hclscope.hclScope.TransitionBody#getTransitionoperation <em>Transitionoperation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Transitionoperation</em>'.
   * @see org.xtext.example.hclscope.hclScope.TransitionBody#getTransitionoperation()
   * @see #getTransitionBody()
   * @generated
   */
  EReference getTransitionBody_Transitionoperation();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.TransitionGuard <em>Transition Guard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition Guard</em>'.
   * @see org.xtext.example.hclscope.hclScope.TransitionGuard
   * @generated
   */
  EClass getTransitionGuard();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hclscope.hclScope.TransitionGuard#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hclscope.hclScope.TransitionGuard#getName()
   * @see #getTransitionGuard()
   * @generated
   */
  EAttribute getTransitionGuard_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.TransitionOperation <em>Transition Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition Operation</em>'.
   * @see org.xtext.example.hclscope.hclScope.TransitionOperation
   * @generated
   */
  EClass getTransitionOperation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hclscope.hclScope.TransitionOperation#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hclscope.hclScope.TransitionOperation#getName()
   * @see #getTransitionOperation()
   * @generated
   */
  EAttribute getTransitionOperation_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.Trigger <em>Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trigger</em>'.
   * @see org.xtext.example.hclscope.hclScope.Trigger
   * @generated
   */
  EClass getTrigger();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hclscope.hclScope.Trigger#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hclscope.hclScope.Trigger#getName()
   * @see #getTrigger()
   * @generated
   */
  EAttribute getTrigger_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.Method <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Method</em>'.
   * @see org.xtext.example.hclscope.hclScope.Method
   * @generated
   */
  EClass getMethod();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hclscope.hclScope.Method#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hclscope.hclScope.Method#getName()
   * @see #getMethod()
   * @generated
   */
  EAttribute getMethod_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see org.xtext.example.hclscope.hclScope.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hclscope.hclScope.Parameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hclscope.hclScope.Parameter#getName()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.MethodParameterTrigger <em>Method Parameter Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Method Parameter Trigger</em>'.
   * @see org.xtext.example.hclscope.hclScope.MethodParameterTrigger
   * @generated
   */
  EClass getMethodParameterTrigger();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.hclscope.hclScope.MethodParameterTrigger#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Method</em>'.
   * @see org.xtext.example.hclscope.hclScope.MethodParameterTrigger#getMethod()
   * @see #getMethodParameterTrigger()
   * @generated
   */
  EReference getMethodParameterTrigger_Method();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.hclscope.hclScope.MethodParameterTrigger#getParameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parameter</em>'.
   * @see org.xtext.example.hclscope.hclScope.MethodParameterTrigger#getParameter()
   * @see #getMethodParameterTrigger()
   * @generated
   */
  EReference getMethodParameterTrigger_Parameter();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.Port <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Port</em>'.
   * @see org.xtext.example.hclscope.hclScope.Port
   * @generated
   */
  EClass getPort();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hclscope.hclScope.Port#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hclscope.hclScope.Port#getName()
   * @see #getPort()
   * @generated
   */
  EAttribute getPort_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see org.xtext.example.hclscope.hclScope.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hclscope.hclScope.Event#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hclscope.hclScope.Event#getName()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.PortEventTrigger <em>Port Event Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Port Event Trigger</em>'.
   * @see org.xtext.example.hclscope.hclScope.PortEventTrigger
   * @generated
   */
  EClass getPortEventTrigger();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.hclscope.hclScope.PortEventTrigger#getPort <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Port</em>'.
   * @see org.xtext.example.hclscope.hclScope.PortEventTrigger#getPort()
   * @see #getPortEventTrigger()
   * @generated
   */
  EReference getPortEventTrigger_Port();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.hclscope.hclScope.PortEventTrigger#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Event</em>'.
   * @see org.xtext.example.hclscope.hclScope.PortEventTrigger#getEvent()
   * @see #getPortEventTrigger()
   * @generated
   */
  EReference getPortEventTrigger_Event();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.Vertex <em>Vertex</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vertex</em>'.
   * @see org.xtext.example.hclscope.hclScope.Vertex
   * @generated
   */
  EClass getVertex();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hclscope.hclScope.Vertex#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hclscope.hclScope.Vertex#getName()
   * @see #getVertex()
   * @generated
   */
  EAttribute getVertex_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.hclscope.hclScope.Transitions <em>Transitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transitions</em>'.
   * @see org.xtext.example.hclscope.hclScope.Transitions
   * @generated
   */
  EClass getTransitions();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.hclscope.hclScope.Transitions#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.hclscope.hclScope.Transitions#getName()
   * @see #getTransitions()
   * @generated
   */
  EAttribute getTransitions_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.hclscope.hclScope.Transitions#getTransitionbody <em>Transitionbody</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Transitionbody</em>'.
   * @see org.xtext.example.hclscope.hclScope.Transitions#getTransitionbody()
   * @see #getTransitions()
   * @generated
   */
  EReference getTransitions_Transitionbody();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  HclScopeFactory getHclScopeFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.StateMachineImpl <em>State Machine</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.StateMachineImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getStateMachine()
     * @generated
     */
    EClass STATE_MACHINE = eINSTANCE.getStateMachine();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE_MACHINE__NAME = eINSTANCE.getStateMachine_Name();

    /**
     * The meta object literal for the '<em><b>States</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE_MACHINE__STATES = eINSTANCE.getStateMachine_States();

    /**
     * The meta object literal for the '<em><b>Initialtransition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE_MACHINE__INITIALTRANSITION = eINSTANCE.getStateMachine_Initialtransition();

    /**
     * The meta object literal for the '<em><b>Junction</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE_MACHINE__JUNCTION = eINSTANCE.getStateMachine_Junction();

    /**
     * The meta object literal for the '<em><b>Choice</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE_MACHINE__CHOICE = eINSTANCE.getStateMachine_Choice();

    /**
     * The meta object literal for the '<em><b>Transition</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE_MACHINE__TRANSITION = eINSTANCE.getStateMachine_Transition();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.StateImpl <em>State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.StateImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getState()
     * @generated
     */
    EClass STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '<em><b>Internaltransition</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__INTERNALTRANSITION = eINSTANCE.getState_Internaltransition();

    /**
     * The meta object literal for the '<em><b>Entryaction</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__ENTRYACTION = eINSTANCE.getState_Entryaction();

    /**
     * The meta object literal for the '<em><b>Exitaction</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__EXITACTION = eINSTANCE.getState_Exitaction();

    /**
     * The meta object literal for the '<em><b>Entrypoint</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__ENTRYPOINT = eINSTANCE.getState_Entrypoint();

    /**
     * The meta object literal for the '<em><b>Exitpoint</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__EXITPOINT = eINSTANCE.getState_Exitpoint();

    /**
     * The meta object literal for the '<em><b>States</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__STATES = eINSTANCE.getState_States();

    /**
     * The meta object literal for the '<em><b>Initialtransition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__INITIALTRANSITION = eINSTANCE.getState_Initialtransition();

    /**
     * The meta object literal for the '<em><b>Junction</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__JUNCTION = eINSTANCE.getState_Junction();

    /**
     * The meta object literal for the '<em><b>Choice</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__CHOICE = eINSTANCE.getState_Choice();

    /**
     * The meta object literal for the '<em><b>Transition</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__TRANSITION = eINSTANCE.getState_Transition();

    /**
     * The meta object literal for the '<em><b>Historytransition</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__HISTORYTRANSITION = eINSTANCE.getState_Historytransition();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.EntryActionImpl <em>Entry Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.EntryActionImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getEntryAction()
     * @generated
     */
    EClass ENTRY_ACTION = eINSTANCE.getEntryAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTRY_ACTION__NAME = eINSTANCE.getEntryAction_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.ExitActionImpl <em>Exit Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.ExitActionImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getExitAction()
     * @generated
     */
    EClass EXIT_ACTION = eINSTANCE.getExitAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXIT_ACTION__NAME = eINSTANCE.getExitAction_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.InitialStateImpl <em>Initial State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.InitialStateImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getInitialState()
     * @generated
     */
    EClass INITIAL_STATE = eINSTANCE.getInitialState();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INITIAL_STATE__NAME = eINSTANCE.getInitialState_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.JunctionImpl <em>Junction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.JunctionImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getJunction()
     * @generated
     */
    EClass JUNCTION = eINSTANCE.getJunction();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.ChoiceImpl <em>Choice</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.ChoiceImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getChoice()
     * @generated
     */
    EClass CHOICE = eINSTANCE.getChoice();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.EntryPointImpl <em>Entry Point</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.EntryPointImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getEntryPoint()
     * @generated
     */
    EClass ENTRY_POINT = eINSTANCE.getEntryPoint();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.ExitPointImpl <em>Exit Point</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.ExitPointImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getExitPoint()
     * @generated
     */
    EClass EXIT_POINT = eINSTANCE.getExitPoint();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.DeepHistoryImpl <em>Deep History</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.DeepHistoryImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getDeepHistory()
     * @generated
     */
    EClass DEEP_HISTORY = eINSTANCE.getDeepHistory();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEEP_HISTORY__NAME = eINSTANCE.getDeepHistory_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.InitialTransitionImpl <em>Initial Transition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.InitialTransitionImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getInitialTransition()
     * @generated
     */
    EClass INITIAL_TRANSITION = eINSTANCE.getInitialTransition();

    /**
     * The meta object literal for the '<em><b>Initialstate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INITIAL_TRANSITION__INITIALSTATE = eINSTANCE.getInitialTransition_Initialstate();

    /**
     * The meta object literal for the '<em><b>Initialto</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INITIAL_TRANSITION__INITIALTO = eINSTANCE.getInitialTransition_Initialto();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.TransitionImpl <em>Transition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.TransitionImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getTransition()
     * @generated
     */
    EClass TRANSITION = eINSTANCE.getTransition();

    /**
     * The meta object literal for the '<em><b>From</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__FROM = eINSTANCE.getTransition_From();

    /**
     * The meta object literal for the '<em><b>To</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__TO = eINSTANCE.getTransition_To();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.InternalTransitionImpl <em>Internal Transition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.InternalTransitionImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getInternalTransition()
     * @generated
     */
    EClass INTERNAL_TRANSITION = eINSTANCE.getInternalTransition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERNAL_TRANSITION__NAME = eINSTANCE.getInternalTransition_Name();

    /**
     * The meta object literal for the '<em><b>Transitionbody</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERNAL_TRANSITION__TRANSITIONBODY = eINSTANCE.getInternalTransition_Transitionbody();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.HistoryTransitionImpl <em>History Transition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.HistoryTransitionImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getHistoryTransition()
     * @generated
     */
    EClass HISTORY_TRANSITION = eINSTANCE.getHistoryTransition();

    /**
     * The meta object literal for the '<em><b>From</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HISTORY_TRANSITION__FROM = eINSTANCE.getHistoryTransition_From();

    /**
     * The meta object literal for the '<em><b>To</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HISTORY_TRANSITION__TO = eINSTANCE.getHistoryTransition_To();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.TransitionBodyImpl <em>Transition Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.TransitionBodyImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getTransitionBody()
     * @generated
     */
    EClass TRANSITION_BODY = eINSTANCE.getTransitionBody();

    /**
     * The meta object literal for the '<em><b>Methodparameter</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION_BODY__METHODPARAMETER = eINSTANCE.getTransitionBody_Methodparameter();

    /**
     * The meta object literal for the '<em><b>Portevent</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION_BODY__PORTEVENT = eINSTANCE.getTransitionBody_Portevent();

    /**
     * The meta object literal for the '<em><b>Trigger</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION_BODY__TRIGGER = eINSTANCE.getTransitionBody_Trigger();

    /**
     * The meta object literal for the '<em><b>Transitionguard</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION_BODY__TRANSITIONGUARD = eINSTANCE.getTransitionBody_Transitionguard();

    /**
     * The meta object literal for the '<em><b>Transitionoperation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION_BODY__TRANSITIONOPERATION = eINSTANCE.getTransitionBody_Transitionoperation();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.TransitionGuardImpl <em>Transition Guard</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.TransitionGuardImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getTransitionGuard()
     * @generated
     */
    EClass TRANSITION_GUARD = eINSTANCE.getTransitionGuard();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION_GUARD__NAME = eINSTANCE.getTransitionGuard_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.TransitionOperationImpl <em>Transition Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.TransitionOperationImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getTransitionOperation()
     * @generated
     */
    EClass TRANSITION_OPERATION = eINSTANCE.getTransitionOperation();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION_OPERATION__NAME = eINSTANCE.getTransitionOperation_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.TriggerImpl <em>Trigger</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.TriggerImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getTrigger()
     * @generated
     */
    EClass TRIGGER = eINSTANCE.getTrigger();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER__NAME = eINSTANCE.getTrigger_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.MethodImpl <em>Method</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.MethodImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getMethod()
     * @generated
     */
    EClass METHOD = eINSTANCE.getMethod();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD__NAME = eINSTANCE.getMethod_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.ParameterImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__NAME = eINSTANCE.getParameter_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.MethodParameterTriggerImpl <em>Method Parameter Trigger</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.MethodParameterTriggerImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getMethodParameterTrigger()
     * @generated
     */
    EClass METHOD_PARAMETER_TRIGGER = eINSTANCE.getMethodParameterTrigger();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD_PARAMETER_TRIGGER__METHOD = eINSTANCE.getMethodParameterTrigger_Method();

    /**
     * The meta object literal for the '<em><b>Parameter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHOD_PARAMETER_TRIGGER__PARAMETER = eINSTANCE.getMethodParameterTrigger_Parameter();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.PortImpl <em>Port</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.PortImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getPort()
     * @generated
     */
    EClass PORT = eINSTANCE.getPort();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PORT__NAME = eINSTANCE.getPort_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.EventImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__NAME = eINSTANCE.getEvent_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.PortEventTriggerImpl <em>Port Event Trigger</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.PortEventTriggerImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getPortEventTrigger()
     * @generated
     */
    EClass PORT_EVENT_TRIGGER = eINSTANCE.getPortEventTrigger();

    /**
     * The meta object literal for the '<em><b>Port</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PORT_EVENT_TRIGGER__PORT = eINSTANCE.getPortEventTrigger_Port();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PORT_EVENT_TRIGGER__EVENT = eINSTANCE.getPortEventTrigger_Event();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.VertexImpl <em>Vertex</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.VertexImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getVertex()
     * @generated
     */
    EClass VERTEX = eINSTANCE.getVertex();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTEX__NAME = eINSTANCE.getVertex_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.hclscope.hclScope.impl.TransitionsImpl <em>Transitions</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.hclscope.hclScope.impl.TransitionsImpl
     * @see org.xtext.example.hclscope.hclScope.impl.HclScopePackageImpl#getTransitions()
     * @generated
     */
    EClass TRANSITIONS = eINSTANCE.getTransitions();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITIONS__NAME = eINSTANCE.getTransitions_Name();

    /**
     * The meta object literal for the '<em><b>Transitionbody</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITIONS__TRANSITIONBODY = eINSTANCE.getTransitions_Transitionbody();

  }

} //HclScopePackage
