/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.hclscope.hclScope;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.hclscope.hclScope.State#getInternaltransition <em>Internaltransition</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.State#getEntryaction <em>Entryaction</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.State#getExitaction <em>Exitaction</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.State#getEntrypoint <em>Entrypoint</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.State#getExitpoint <em>Exitpoint</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.State#getStates <em>States</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.State#getInitialtransition <em>Initialtransition</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.State#getJunction <em>Junction</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.State#getChoice <em>Choice</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.State#getTransition <em>Transition</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.State#getHistorytransition <em>Historytransition</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getState()
 * @model
 * @generated
 */
public interface State extends Vertex
{
  /**
   * Returns the value of the '<em><b>Internaltransition</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.hclscope.hclScope.InternalTransition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Internaltransition</em>' containment reference list.
   * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getState_Internaltransition()
   * @model containment="true"
   * @generated
   */
  EList<InternalTransition> getInternaltransition();

  /**
   * Returns the value of the '<em><b>Entryaction</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.hclscope.hclScope.EntryAction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entryaction</em>' containment reference list.
   * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getState_Entryaction()
   * @model containment="true"
   * @generated
   */
  EList<EntryAction> getEntryaction();

  /**
   * Returns the value of the '<em><b>Exitaction</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.hclscope.hclScope.ExitAction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exitaction</em>' containment reference list.
   * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getState_Exitaction()
   * @model containment="true"
   * @generated
   */
  EList<ExitAction> getExitaction();

  /**
   * Returns the value of the '<em><b>Entrypoint</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.hclscope.hclScope.EntryPoint}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entrypoint</em>' containment reference list.
   * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getState_Entrypoint()
   * @model containment="true"
   * @generated
   */
  EList<EntryPoint> getEntrypoint();

  /**
   * Returns the value of the '<em><b>Exitpoint</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.hclscope.hclScope.ExitPoint}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exitpoint</em>' containment reference list.
   * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getState_Exitpoint()
   * @model containment="true"
   * @generated
   */
  EList<ExitPoint> getExitpoint();

  /**
   * Returns the value of the '<em><b>States</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.hclscope.hclScope.State}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>States</em>' containment reference list.
   * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getState_States()
   * @model containment="true"
   * @generated
   */
  EList<State> getStates();

  /**
   * Returns the value of the '<em><b>Initialtransition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initialtransition</em>' containment reference.
   * @see #setInitialtransition(InitialTransition)
   * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getState_Initialtransition()
   * @model containment="true"
   * @generated
   */
  InitialTransition getInitialtransition();

  /**
   * Sets the value of the '{@link org.xtext.example.hclscope.hclScope.State#getInitialtransition <em>Initialtransition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initialtransition</em>' containment reference.
   * @see #getInitialtransition()
   * @generated
   */
  void setInitialtransition(InitialTransition value);

  /**
   * Returns the value of the '<em><b>Junction</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.hclscope.hclScope.Junction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Junction</em>' containment reference list.
   * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getState_Junction()
   * @model containment="true"
   * @generated
   */
  EList<Junction> getJunction();

  /**
   * Returns the value of the '<em><b>Choice</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.hclscope.hclScope.Choice}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Choice</em>' containment reference list.
   * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getState_Choice()
   * @model containment="true"
   * @generated
   */
  EList<Choice> getChoice();

  /**
   * Returns the value of the '<em><b>Transition</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.hclscope.hclScope.Transition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transition</em>' containment reference list.
   * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getState_Transition()
   * @model containment="true"
   * @generated
   */
  EList<Transition> getTransition();

  /**
   * Returns the value of the '<em><b>Historytransition</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.hclscope.hclScope.HistoryTransition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Historytransition</em>' containment reference list.
   * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getState_Historytransition()
   * @model containment="true"
   * @generated
   */
  EList<HistoryTransition> getHistorytransition();

} // State
