/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.hclscope.hclScope;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.hclscope.hclScope.Transition#getFrom <em>From</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.Transition#getTo <em>To</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getTransition()
 * @model
 * @generated
 */
public interface Transition extends Transitions
{
  /**
   * Returns the value of the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' reference.
   * @see #setFrom(Vertex)
   * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getTransition_From()
   * @model
   * @generated
   */
  Vertex getFrom();

  /**
   * Sets the value of the '{@link org.xtext.example.hclscope.hclScope.Transition#getFrom <em>From</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' reference.
   * @see #getFrom()
   * @generated
   */
  void setFrom(Vertex value);

  /**
   * Returns the value of the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' reference.
   * @see #setTo(Vertex)
   * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getTransition_To()
   * @model
   * @generated
   */
  Vertex getTo();

  /**
   * Sets the value of the '{@link org.xtext.example.hclscope.hclScope.Transition#getTo <em>To</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' reference.
   * @see #getTo()
   * @generated
   */
  void setTo(Vertex value);

} // Transition
