/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.hclscope.hclScope;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transition Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.hclscope.hclScope.TransitionBody#getMethodparameter <em>Methodparameter</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.TransitionBody#getPortevent <em>Portevent</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.TransitionBody#getTrigger <em>Trigger</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.TransitionBody#getTransitionguard <em>Transitionguard</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.TransitionBody#getTransitionoperation <em>Transitionoperation</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getTransitionBody()
 * @model
 * @generated
 */
public interface TransitionBody extends EObject
{
  /**
   * Returns the value of the '<em><b>Methodparameter</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.hclscope.hclScope.MethodParameterTrigger}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Methodparameter</em>' containment reference list.
   * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getTransitionBody_Methodparameter()
   * @model containment="true"
   * @generated
   */
  EList<MethodParameterTrigger> getMethodparameter();

  /**
   * Returns the value of the '<em><b>Portevent</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.hclscope.hclScope.PortEventTrigger}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Portevent</em>' containment reference list.
   * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getTransitionBody_Portevent()
   * @model containment="true"
   * @generated
   */
  EList<PortEventTrigger> getPortevent();

  /**
   * Returns the value of the '<em><b>Trigger</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.hclscope.hclScope.Trigger}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trigger</em>' containment reference list.
   * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getTransitionBody_Trigger()
   * @model containment="true"
   * @generated
   */
  EList<Trigger> getTrigger();

  /**
   * Returns the value of the '<em><b>Transitionguard</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transitionguard</em>' containment reference.
   * @see #setTransitionguard(TransitionGuard)
   * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getTransitionBody_Transitionguard()
   * @model containment="true"
   * @generated
   */
  TransitionGuard getTransitionguard();

  /**
   * Sets the value of the '{@link org.xtext.example.hclscope.hclScope.TransitionBody#getTransitionguard <em>Transitionguard</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transitionguard</em>' containment reference.
   * @see #getTransitionguard()
   * @generated
   */
  void setTransitionguard(TransitionGuard value);

  /**
   * Returns the value of the '<em><b>Transitionoperation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transitionoperation</em>' containment reference.
   * @see #setTransitionoperation(TransitionOperation)
   * @see org.xtext.example.hclscope.hclScope.HclScopePackage#getTransitionBody_Transitionoperation()
   * @model containment="true"
   * @generated
   */
  TransitionOperation getTransitionoperation();

  /**
   * Sets the value of the '{@link org.xtext.example.hclscope.hclScope.TransitionBody#getTransitionoperation <em>Transitionoperation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transitionoperation</em>' containment reference.
   * @see #getTransitionoperation()
   * @generated
   */
  void setTransitionoperation(TransitionOperation value);

} // TransitionBody
