/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.hclscope;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class HclScopeStandaloneSetup extends HclScopeStandaloneSetupGenerated {

	public static void doSetup() {
		new HclScopeStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
