/*
 * generated by Xtext
 */
package org.eclipse.papyrusrt.xtumlrt.xtext.ui.contentassist

import org.eclipse.papyrusrt.xtumlrt.xtext.ui.contentassist.AbstractUmlrtProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class UmlrtProposalProvider extends AbstractUmlrtProposalProvider {
}
