<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="umlext" nsURI="http://www.eclipse.org/papyrus/umlrt/uml-ext"
    nsPrefix="umlext">
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eOperations name="getExtension" ordered="false" lowerBound="1" eType="#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedVisibility" value="true"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getExcludedElements" ordered="false" upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedVisibility" value="true"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendedElement" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Element"
        resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The UML model element that is extended by my features.&#xA;This is a non-resolving reference to ensure that attempts&#xA;to access the extension of an unloaded element does not&#xA;re-load its resource."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extension" ordered="false"
        lowerBound="1" eType="#//Element" changeable="false" volatile="true" transient="true"
        derived="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This looks odd as a required self-reference, but it is actually meant&#xA;to be accessed as an extension feature of the extended UML model&#xA;element, in order to access the extension object."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitOwnedElement" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Element"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="union"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="excludedElement" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Element"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace" abstract="true" eSuperTypes="#//Element">
    <eOperations name="getExcludedMembers" ordered="false" upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//NamedElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedVisibility" value="true"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitOwnedMember" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//NamedElement"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="union"/>
      <eAnnotations source="subsets" references="#//Element/implicitOwnedElement"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="excludedMember" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//NamedElement"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="subsets" references="#//Element/excludedElement"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitOwnedRule" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Constraint"
        containment="true">
      <eAnnotations source="subsets" references="#//Namespace/implicitOwnedMember"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BehavioredClassifier" abstract="true"
      eSuperTypes="#//Namespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitBehavior" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Behavior"
        containment="true">
      <eAnnotations source="subsets" references="#//Namespace/implicitOwnedMember"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuredClassifier" abstract="true"
      eSuperTypes="#//Namespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitAttribute" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Property"
        containment="true">
      <eAnnotations source="subsets" references="#//Namespace/implicitOwnedMember"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitConnector" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Connector"
        containment="true">
      <eAnnotations source="subsets" references="#//Namespace/implicitOwnedMember"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EncapsulatedClassifier" abstract="true"
      eSuperTypes="#//StructuredClassifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitPort" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Port"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="subsets" references="#//StructuredClassifier/implicitAttribute"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//EncapsulatedClassifier #//BehavioredClassifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitOperation" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Operation"
        containment="true">
      <eAnnotations source="subsets" references="#//Namespace/implicitOwnedMember"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//Namespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitOperation" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Operation"
        containment="true">
      <eAnnotations source="subsets" references="#//Namespace/implicitOwnedMember"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine" eSuperTypes="#//Namespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitRegion" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Region"
        containment="true">
      <eAnnotations source="subsets" references="#//Namespace/implicitOwnedMember"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitConnectionPoint"
        ordered="false" upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Pseudostate"
        containment="true">
      <eAnnotations source="subsets" references="#//Namespace/implicitOwnedMember"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Region" eSuperTypes="#//Namespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitSubvertex" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Vertex"
        containment="true">
      <eAnnotations source="subsets" references="#//Namespace/implicitOwnedMember"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitTransition" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Transition"
        containment="true">
      <eAnnotations source="subsets" references="#//Namespace/implicitOwnedMember"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//Namespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitTrigger" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Trigger"
        containment="true">
      <eAnnotations source="subsets" references="#//Element/implicitOwnedElement"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//Namespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitRegion" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Region"
        containment="true">
      <eAnnotations source="subsets" references="#//Namespace/implicitOwnedMember"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implicitConnectionPoint"
        ordered="false" upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Pseudostate"
        containment="true">
      <eAnnotations source="subsets" references="#//Namespace/implicitOwnedMember"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
