/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.hclscope.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractHclScopeScopeProvider extends DelegatingScopeProvider {
}
