<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="platformcppmodel" nsURI="http://www.eclipse.org/papyrusrt/xtumlrt/platformcppmodel"
    nsPrefix="platformcppmodel">
  <eClassifiers xsi:type="ecore:EClass" name="CppInclude" eSuperTypes="../../org.eclipse.papyrusrt.xtumlrt.platform.model/model/platformmodel.ecore#//PlatformElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="header" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CppPtr" eSuperTypes="../../org.eclipse.papyrusrt.xtumlrt.platform.model/model/platformmodel.ecore#//PlatformElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="declaration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenerationProperties" eSuperTypes="../../org.eclipse.papyrusrt.xtumlrt.platform.model/model/platformmodel.ecore#//PlatformElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
</ecore:EPackage>
