/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.hclscope.hclScope.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.hclscope.hclScope.ExitPoint;
import org.xtext.example.hclscope.hclScope.HclScopePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exit Point</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExitPointImpl extends VertexImpl implements ExitPoint
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExitPointImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HclScopePackage.Literals.EXIT_POINT;
  }

} //ExitPointImpl
