/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.hclscope.hclScope.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.hclscope.hclScope.Choice;
import org.xtext.example.hclscope.hclScope.HclScopePackage;
import org.xtext.example.hclscope.hclScope.InitialTransition;
import org.xtext.example.hclscope.hclScope.Junction;
import org.xtext.example.hclscope.hclScope.State;
import org.xtext.example.hclscope.hclScope.StateMachine;
import org.xtext.example.hclscope.hclScope.Transition;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>State Machine</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.hclscope.hclScope.impl.StateMachineImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.impl.StateMachineImpl#getStates <em>States</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.impl.StateMachineImpl#getInitialtransition <em>Initialtransition</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.impl.StateMachineImpl#getJunction <em>Junction</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.impl.StateMachineImpl#getChoice <em>Choice</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.impl.StateMachineImpl#getTransition <em>Transition</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StateMachineImpl extends MinimalEObjectImpl.Container implements StateMachine
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getStates() <em>States</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStates()
   * @generated
   * @ordered
   */
  protected EList<State> states;

  /**
   * The cached value of the '{@link #getInitialtransition() <em>Initialtransition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitialtransition()
   * @generated
   * @ordered
   */
  protected InitialTransition initialtransition;

  /**
   * The cached value of the '{@link #getJunction() <em>Junction</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJunction()
   * @generated
   * @ordered
   */
  protected EList<Junction> junction;

  /**
   * The cached value of the '{@link #getChoice() <em>Choice</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChoice()
   * @generated
   * @ordered
   */
  protected EList<Choice> choice;

  /**
   * The cached value of the '{@link #getTransition() <em>Transition</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTransition()
   * @generated
   * @ordered
   */
  protected EList<Transition> transition;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StateMachineImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HclScopePackage.Literals.STATE_MACHINE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HclScopePackage.STATE_MACHINE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<State> getStates()
  {
    if (states == null)
    {
      states = new EObjectContainmentEList<State>(State.class, this, HclScopePackage.STATE_MACHINE__STATES);
    }
    return states;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InitialTransition getInitialtransition()
  {
    return initialtransition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInitialtransition(InitialTransition newInitialtransition, NotificationChain msgs)
  {
    InitialTransition oldInitialtransition = initialtransition;
    initialtransition = newInitialtransition;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, HclScopePackage.STATE_MACHINE__INITIALTRANSITION, oldInitialtransition, newInitialtransition);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInitialtransition(InitialTransition newInitialtransition)
  {
    if (newInitialtransition != initialtransition)
    {
      NotificationChain msgs = null;
      if (initialtransition != null)
        msgs = ((InternalEObject)initialtransition).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - HclScopePackage.STATE_MACHINE__INITIALTRANSITION, null, msgs);
      if (newInitialtransition != null)
        msgs = ((InternalEObject)newInitialtransition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - HclScopePackage.STATE_MACHINE__INITIALTRANSITION, null, msgs);
      msgs = basicSetInitialtransition(newInitialtransition, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HclScopePackage.STATE_MACHINE__INITIALTRANSITION, newInitialtransition, newInitialtransition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Junction> getJunction()
  {
    if (junction == null)
    {
      junction = new EObjectContainmentEList<Junction>(Junction.class, this, HclScopePackage.STATE_MACHINE__JUNCTION);
    }
    return junction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Choice> getChoice()
  {
    if (choice == null)
    {
      choice = new EObjectContainmentEList<Choice>(Choice.class, this, HclScopePackage.STATE_MACHINE__CHOICE);
    }
    return choice;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Transition> getTransition()
  {
    if (transition == null)
    {
      transition = new EObjectContainmentEList<Transition>(Transition.class, this, HclScopePackage.STATE_MACHINE__TRANSITION);
    }
    return transition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case HclScopePackage.STATE_MACHINE__STATES:
        return ((InternalEList<?>)getStates()).basicRemove(otherEnd, msgs);
      case HclScopePackage.STATE_MACHINE__INITIALTRANSITION:
        return basicSetInitialtransition(null, msgs);
      case HclScopePackage.STATE_MACHINE__JUNCTION:
        return ((InternalEList<?>)getJunction()).basicRemove(otherEnd, msgs);
      case HclScopePackage.STATE_MACHINE__CHOICE:
        return ((InternalEList<?>)getChoice()).basicRemove(otherEnd, msgs);
      case HclScopePackage.STATE_MACHINE__TRANSITION:
        return ((InternalEList<?>)getTransition()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case HclScopePackage.STATE_MACHINE__NAME:
        return getName();
      case HclScopePackage.STATE_MACHINE__STATES:
        return getStates();
      case HclScopePackage.STATE_MACHINE__INITIALTRANSITION:
        return getInitialtransition();
      case HclScopePackage.STATE_MACHINE__JUNCTION:
        return getJunction();
      case HclScopePackage.STATE_MACHINE__CHOICE:
        return getChoice();
      case HclScopePackage.STATE_MACHINE__TRANSITION:
        return getTransition();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case HclScopePackage.STATE_MACHINE__NAME:
        setName((String)newValue);
        return;
      case HclScopePackage.STATE_MACHINE__STATES:
        getStates().clear();
        getStates().addAll((Collection<? extends State>)newValue);
        return;
      case HclScopePackage.STATE_MACHINE__INITIALTRANSITION:
        setInitialtransition((InitialTransition)newValue);
        return;
      case HclScopePackage.STATE_MACHINE__JUNCTION:
        getJunction().clear();
        getJunction().addAll((Collection<? extends Junction>)newValue);
        return;
      case HclScopePackage.STATE_MACHINE__CHOICE:
        getChoice().clear();
        getChoice().addAll((Collection<? extends Choice>)newValue);
        return;
      case HclScopePackage.STATE_MACHINE__TRANSITION:
        getTransition().clear();
        getTransition().addAll((Collection<? extends Transition>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case HclScopePackage.STATE_MACHINE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case HclScopePackage.STATE_MACHINE__STATES:
        getStates().clear();
        return;
      case HclScopePackage.STATE_MACHINE__INITIALTRANSITION:
        setInitialtransition((InitialTransition)null);
        return;
      case HclScopePackage.STATE_MACHINE__JUNCTION:
        getJunction().clear();
        return;
      case HclScopePackage.STATE_MACHINE__CHOICE:
        getChoice().clear();
        return;
      case HclScopePackage.STATE_MACHINE__TRANSITION:
        getTransition().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case HclScopePackage.STATE_MACHINE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case HclScopePackage.STATE_MACHINE__STATES:
        return states != null && !states.isEmpty();
      case HclScopePackage.STATE_MACHINE__INITIALTRANSITION:
        return initialtransition != null;
      case HclScopePackage.STATE_MACHINE__JUNCTION:
        return junction != null && !junction.isEmpty();
      case HclScopePackage.STATE_MACHINE__CHOICE:
        return choice != null && !choice.isEmpty();
      case HclScopePackage.STATE_MACHINE__TRANSITION:
        return transition != null && !transition.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //StateMachineImpl
