/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.hclscope.hclScope.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.hclscope.hclScope.HclScopePackage;
import org.xtext.example.hclscope.hclScope.MethodParameterTrigger;
import org.xtext.example.hclscope.hclScope.PortEventTrigger;
import org.xtext.example.hclscope.hclScope.TransitionBody;
import org.xtext.example.hclscope.hclScope.TransitionGuard;
import org.xtext.example.hclscope.hclScope.TransitionOperation;
import org.xtext.example.hclscope.hclScope.Trigger;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Transition Body</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.hclscope.hclScope.impl.TransitionBodyImpl#getMethodparameter <em>Methodparameter</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.impl.TransitionBodyImpl#getPortevent <em>Portevent</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.impl.TransitionBodyImpl#getTrigger <em>Trigger</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.impl.TransitionBodyImpl#getTransitionguard <em>Transitionguard</em>}</li>
 *   <li>{@link org.xtext.example.hclscope.hclScope.impl.TransitionBodyImpl#getTransitionoperation <em>Transitionoperation</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TransitionBodyImpl extends MinimalEObjectImpl.Container implements TransitionBody
{
  /**
   * The cached value of the '{@link #getMethodparameter() <em>Methodparameter</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMethodparameter()
   * @generated
   * @ordered
   */
  protected EList<MethodParameterTrigger> methodparameter;

  /**
   * The cached value of the '{@link #getPortevent() <em>Portevent</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPortevent()
   * @generated
   * @ordered
   */
  protected EList<PortEventTrigger> portevent;

  /**
   * The cached value of the '{@link #getTrigger() <em>Trigger</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTrigger()
   * @generated
   * @ordered
   */
  protected EList<Trigger> trigger;

  /**
   * The cached value of the '{@link #getTransitionguard() <em>Transitionguard</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTransitionguard()
   * @generated
   * @ordered
   */
  protected TransitionGuard transitionguard;

  /**
   * The cached value of the '{@link #getTransitionoperation() <em>Transitionoperation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTransitionoperation()
   * @generated
   * @ordered
   */
  protected TransitionOperation transitionoperation;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TransitionBodyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HclScopePackage.Literals.TRANSITION_BODY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<MethodParameterTrigger> getMethodparameter()
  {
    if (methodparameter == null)
    {
      methodparameter = new EObjectContainmentEList<MethodParameterTrigger>(MethodParameterTrigger.class, this, HclScopePackage.TRANSITION_BODY__METHODPARAMETER);
    }
    return methodparameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<PortEventTrigger> getPortevent()
  {
    if (portevent == null)
    {
      portevent = new EObjectContainmentEList<PortEventTrigger>(PortEventTrigger.class, this, HclScopePackage.TRANSITION_BODY__PORTEVENT);
    }
    return portevent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Trigger> getTrigger()
  {
    if (trigger == null)
    {
      trigger = new EObjectContainmentEList<Trigger>(Trigger.class, this, HclScopePackage.TRANSITION_BODY__TRIGGER);
    }
    return trigger;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TransitionGuard getTransitionguard()
  {
    return transitionguard;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTransitionguard(TransitionGuard newTransitionguard, NotificationChain msgs)
  {
    TransitionGuard oldTransitionguard = transitionguard;
    transitionguard = newTransitionguard;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, HclScopePackage.TRANSITION_BODY__TRANSITIONGUARD, oldTransitionguard, newTransitionguard);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTransitionguard(TransitionGuard newTransitionguard)
  {
    if (newTransitionguard != transitionguard)
    {
      NotificationChain msgs = null;
      if (transitionguard != null)
        msgs = ((InternalEObject)transitionguard).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - HclScopePackage.TRANSITION_BODY__TRANSITIONGUARD, null, msgs);
      if (newTransitionguard != null)
        msgs = ((InternalEObject)newTransitionguard).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - HclScopePackage.TRANSITION_BODY__TRANSITIONGUARD, null, msgs);
      msgs = basicSetTransitionguard(newTransitionguard, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HclScopePackage.TRANSITION_BODY__TRANSITIONGUARD, newTransitionguard, newTransitionguard));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TransitionOperation getTransitionoperation()
  {
    return transitionoperation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTransitionoperation(TransitionOperation newTransitionoperation, NotificationChain msgs)
  {
    TransitionOperation oldTransitionoperation = transitionoperation;
    transitionoperation = newTransitionoperation;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, HclScopePackage.TRANSITION_BODY__TRANSITIONOPERATION, oldTransitionoperation, newTransitionoperation);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTransitionoperation(TransitionOperation newTransitionoperation)
  {
    if (newTransitionoperation != transitionoperation)
    {
      NotificationChain msgs = null;
      if (transitionoperation != null)
        msgs = ((InternalEObject)transitionoperation).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - HclScopePackage.TRANSITION_BODY__TRANSITIONOPERATION, null, msgs);
      if (newTransitionoperation != null)
        msgs = ((InternalEObject)newTransitionoperation).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - HclScopePackage.TRANSITION_BODY__TRANSITIONOPERATION, null, msgs);
      msgs = basicSetTransitionoperation(newTransitionoperation, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HclScopePackage.TRANSITION_BODY__TRANSITIONOPERATION, newTransitionoperation, newTransitionoperation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case HclScopePackage.TRANSITION_BODY__METHODPARAMETER:
        return ((InternalEList<?>)getMethodparameter()).basicRemove(otherEnd, msgs);
      case HclScopePackage.TRANSITION_BODY__PORTEVENT:
        return ((InternalEList<?>)getPortevent()).basicRemove(otherEnd, msgs);
      case HclScopePackage.TRANSITION_BODY__TRIGGER:
        return ((InternalEList<?>)getTrigger()).basicRemove(otherEnd, msgs);
      case HclScopePackage.TRANSITION_BODY__TRANSITIONGUARD:
        return basicSetTransitionguard(null, msgs);
      case HclScopePackage.TRANSITION_BODY__TRANSITIONOPERATION:
        return basicSetTransitionoperation(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case HclScopePackage.TRANSITION_BODY__METHODPARAMETER:
        return getMethodparameter();
      case HclScopePackage.TRANSITION_BODY__PORTEVENT:
        return getPortevent();
      case HclScopePackage.TRANSITION_BODY__TRIGGER:
        return getTrigger();
      case HclScopePackage.TRANSITION_BODY__TRANSITIONGUARD:
        return getTransitionguard();
      case HclScopePackage.TRANSITION_BODY__TRANSITIONOPERATION:
        return getTransitionoperation();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case HclScopePackage.TRANSITION_BODY__METHODPARAMETER:
        getMethodparameter().clear();
        getMethodparameter().addAll((Collection<? extends MethodParameterTrigger>)newValue);
        return;
      case HclScopePackage.TRANSITION_BODY__PORTEVENT:
        getPortevent().clear();
        getPortevent().addAll((Collection<? extends PortEventTrigger>)newValue);
        return;
      case HclScopePackage.TRANSITION_BODY__TRIGGER:
        getTrigger().clear();
        getTrigger().addAll((Collection<? extends Trigger>)newValue);
        return;
      case HclScopePackage.TRANSITION_BODY__TRANSITIONGUARD:
        setTransitionguard((TransitionGuard)newValue);
        return;
      case HclScopePackage.TRANSITION_BODY__TRANSITIONOPERATION:
        setTransitionoperation((TransitionOperation)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case HclScopePackage.TRANSITION_BODY__METHODPARAMETER:
        getMethodparameter().clear();
        return;
      case HclScopePackage.TRANSITION_BODY__PORTEVENT:
        getPortevent().clear();
        return;
      case HclScopePackage.TRANSITION_BODY__TRIGGER:
        getTrigger().clear();
        return;
      case HclScopePackage.TRANSITION_BODY__TRANSITIONGUARD:
        setTransitionguard((TransitionGuard)null);
        return;
      case HclScopePackage.TRANSITION_BODY__TRANSITIONOPERATION:
        setTransitionoperation((TransitionOperation)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case HclScopePackage.TRANSITION_BODY__METHODPARAMETER:
        return methodparameter != null && !methodparameter.isEmpty();
      case HclScopePackage.TRANSITION_BODY__PORTEVENT:
        return portevent != null && !portevent.isEmpty();
      case HclScopePackage.TRANSITION_BODY__TRIGGER:
        return trigger != null && !trigger.isEmpty();
      case HclScopePackage.TRANSITION_BODY__TRANSITIONGUARD:
        return transitionguard != null;
      case HclScopePackage.TRANSITION_BODY__TRANSITIONOPERATION:
        return transitionoperation != null;
    }
    return super.eIsSet(featureID);
  }

} //TransitionBodyImpl
