<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="systemelements" nsURI="http://www.eclipse.org/papyrus/umlrt/systemelements"
    nsPrefix="SystemElements">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="system elements"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="SystemProtocol">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Collaboration" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Collaboration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseProtocol">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="base_Collaboration.isAbstract"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Collaboration" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Collaboration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
</ecore:EPackage>
